### ISSUE TITLE
Don't depend on systemd

### ISSUE THREAD

**Issue by danimesq** [kpcyrd/yrd#23]
There are Linux distros such as AntiX and Gentoo which doesn't uses systemd. Can't install yrd in those.

**Comment by kpcyrd** [comment]
There is no dependency on systemd, you just have to write your own init script.

**Comment by danimesq** [comment]
yrd can also make CJDNS to function as daemon without requiring systemd?

**Comment by kpcyrd** [comment]
yes, the systemd unit is just used to run a command automatically at boot, but you could also use any other init system for this or even run the commands manually.
