### ISSUE TITLE
Broken On Debian -> raise Exception('failed to load cjdroute.conf as json

### ISSUE THREAD

**Issue by text-editor** [kpcyrd/yrd#5]
all dependencies installed, /etc/cjdroute.conf passes jsonlint

**Comment by kpcyrd** [comment]
Can you please post the exception caused by this command?

```
sudo cat /etc/cjdroute.conf | \
python3 -c 'import json,subprocess,sys;'\
'conf=sys.stdin.buffer.read();'\
'conf=subprocess.Popen(["cjdroute","--cleanconf"],stdin=subprocess.PIPE,stdout=subprocess.PIPE).communicate(conf)[0];'\
'conf=json.loads(str(conf,"ascii"))'
```

**Comment by text-editor** [comment]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.4/json/**init**.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 359, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid \escape: line 64 column 55 (char 2291)

**Comment by kpcyrd** [comment]
that looks like invalid json in line 64 (after `cjdroute --cleanconf`)
