### ISSUE TITLE
Documentation not up to date

### ISSUE THREAD

**Issue by MaximilianKindshofer** [kpcyrd/yrd#6]
yrd a should be yrd address 

yrd n should be yrd neighbours

**Comment by kpcyrd** [comment]
hey @MaximilianKindshofer,

thanks for creating this issue. This is indeed true for the `python-argh` package shipped by debian stable, if you run `yrd` with a recent `argh`, `yrd a` is a shorthand for `yrd address` (same for `yrd n`).

I'm going to mention this in the docs later.

**Comment by kpcyrd** [comment]
debian stable now ships a more recent version of argh that can handle aliases correctly.
